### ISSUE TITLE
Quibble broken on Node v8.5.0

### ISSUE THREAD

**Issue by samhatoum** [testdouble/quibble#14]
Hi

* Given this `test.js` file:
```javascript
import td from 'testdouble';

describe('Quibble', function () {
  it('works', function () {
    td.replace('path');
    require('http');
  });
});
```

* When I run `npx mocha --require babel-register ./test.js` on **Node v8.5.0**

* Then I see:
```
  Quibble
    1) works


  0 passing (55ms)
  1 failing

  1) Quibble
       works:
     TypeError: Module._cache.hasOwnProperty is not a function
      at doWithoutCache (node_modules/testdouble/node_modules/quibble/lib/quibble.js:108:23)
      at Function.fakeLoad [as _load] (node_modules/testdouble/node_modules/quibble/lib/quibble.js:86:14)
      at require (internal/module.js:11:18)
      at Context.<anonymous> (test.js:6:5)
```

This works on Node 6.9.0

**Comment by searls** [comment]
Welp.

**Comment by searls** [comment]
Tried upgrading to Node 8.6.0 to replicate but could not:

```○ {master} ~/code/testdouble/quibble $ node -v; yarn test
v8.6.0
yarn run v1.2.1
$ mocha -u mocha-given -R $npm_package_config_mocha_reporter --compilers coffee:coffee-script --recursive test/helper.coffee test/src/


  ․․․․․․․․․․․․․․․․․․․․․

  21 passing (40ms)

✨  Done in 0.68s.
```

Can you try again on a fresh clone and 8.6? If it's still an issue, provide more info about your environment and we'll reopen to investigate

**Comment by searls** [comment]
Sorry, just now realized you're talking about a custom test, not quibble's own suite

**Comment by searls** [comment]
It was a little confusing to get your example running because it required other modules to be installed that weren't mentioned, but after creating a package.json:

``` json
{
  "name": "lol",
  "version": "1.0.0",
  "description": "",
  "main": "test.js",
  "dependencies": {},
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-env": "^2.4.1",
    "babel-register": "^6.26.0",
    "mocha": "^4.0.1",
    "testdouble": "^3.2.6"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```

And running:

``` 
$ npx mocha --require babel-register ./test.js
```

I get:

```
  Quibble
    ✓ works


  1 passing (30ms)
```

```
$ node -v; npm -v
v8.6.0
5.3.0
```

**Comment by samhatoum** [comment]
Thanks for looking into this @searls. I just tried with your package.json and it works. It looks like I was using an older version of testdouble (and therefore an older version of quibble). I can confirm my report was bogus (sorry about that!) and that it works on 8.5.0 also.

Apologies!
